name: build go

on:
  schedule:
    - cron: '23 4 * * *'

  workflow_dispatch: {}

  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-gotip:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: go
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/seankhliao/go:tip
